server:
  port: 8041
#数据库连接配置信息
spring:
  datasource:
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/management_of_defaulting_customers?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://10.253.44.95:3306/management_of_defaulting_customers?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

