server:
  port: 8040
#数据库连接配置信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/management_of_defaulting_customers?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

